/**
 * Curated Dataset: Latest 50 Paintings with Real Dimensions (in meters)
 * For 3D Walk Around Modern Apartment Exhibition
 */
const WALKAROUND_PAINTINGS = [
    {
        "id": 271,
        "index": 1,
        "title": "Golden Ticket",
        "filename": "271 GOLDEN TICKET.jpg",
        "src": "assets/images/271 GOLDEN TICKET.jpg",
        "size": "40 * 100 cm",
        "widthM": 0.4,
        "heightM": 1,
        "material": "Akrylfärg, glitter",
        "year": "April 2026",
        "description": ""
    },
    {
        "id": 270,
        "index": 2,
        "title": "Origami",
        "filename": "270 ORIGAMI.jpg",
        "src": "assets/images/270 ORIGAMI.jpg",
        "size": "100 * 120 cm",
        "widthM": 1,
        "heightM": 1.2,
        "material": "Akrylfärg, glitter",
        "year": "April 2026",
        "description": ""
    },
    {
        "id": 269,
        "index": 3,
        "title": "Vertigo",
        "filename": "269 VERTIGO.jpg",
        "src": "assets/images/269 VERTIGO.jpg",
        "size": "40 * 100 cm",
        "widthM": 0.4,
        "heightM": 1,
        "material": "Akrylfärg, glitter",
        "year": "April 2026",
        "description": ""
    },
    {
        "id": 268,
        "index": 4,
        "title": "Raspberry Beret",
        "filename": "268 RASPBERRY BERET.jpg",
        "src": "assets/images/268 RASPBERRY BERET.jpg",
        "size": "40 * 100 cm",
        "widthM": 0.4,
        "heightM": 1,
        "material": "Akrylfärg, lim, glitter, smycken",
        "year": "Januari 2026",
        "description": ""
    },
    {
        "id": 267,
        "index": 5,
        "title": "Pink Dress",
        "filename": "267 PINK DRESS.jpg",
        "src": "assets/images/267 PINK DRESS.jpg",
        "size": "100 * 120 cm",
        "widthM": 1,
        "heightM": 1.2,
        "material": "Akrylfärg, resin",
        "year": "Deceber 2025",
        "description": ""
    },
    {
        "id": 266,
        "index": 6,
        "title": "Black Mirror",
        "filename": "266 BLACK MIRROR.jpg",
        "src": "assets/images/266 BLACK MIRROR.jpg",
        "size": "160 * 100 cm",
        "widthM": 1.6,
        "heightM": 1,
        "material": "Akrylfärg, resin",
        "year": "Septemner 2024",
        "description": ""
    },
    {
        "id": 265,
        "index": 7,
        "title": "My Heart Has Teeth",
        "filename": "265 MY HEART HAS TEETH.jpg",
        "src": "assets/images/265 MY HEART HAS TEETH.jpg",
        "size": "160 * 100 cm",
        "widthM": 1.6,
        "heightM": 1,
        "material": "Akrylfärg, resin",
        "year": "2024",
        "description": ""
    },
    {
        "id": 264,
        "index": 8,
        "title": "Warmpop",
        "filename": "264 WARMPOP.jpg",
        "src": "assets/images/264 WARMPOP.jpg",
        "size": "40 * 40 cm",
        "widthM": 0.4,
        "heightM": 0.4,
        "material": "Akrylfärg, resin",
        "year": "Augusti 2024",
        "description": ""
    },
    {
        "id": 263,
        "index": 9,
        "title": "Grapefruit",
        "filename": "263 GRAPEFRUIT.jpg",
        "src": "assets/images/263 GRAPEFRUIT.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg, resin",
        "year": "Augusti 2024",
        "description": ""
    },
    {
        "id": 262,
        "index": 10,
        "title": "Love In Lo-fi",
        "filename": "262 LOVE IN LO-FI.jpg",
        "src": "assets/images/262 LOVE IN LO-FI.jpg",
        "size": "40 * 40 cm",
        "widthM": 0.4,
        "heightM": 0.4,
        "material": "Akrylfärg, sprayfärg, glitterspray, glitter, resin",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 261,
        "index": 11,
        "title": "Pearls",
        "filename": "261 PEARLS.jpg",
        "src": "assets/images/261 PEARLS.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg, resin",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 260,
        "index": 12,
        "title": "Who Knew",
        "filename": "260 WHO KNEW.jpg",
        "src": "assets/images/260 WHO KNEW.jpg",
        "size": "50 * 50 cm",
        "widthM": 0.5,
        "heightM": 0.5,
        "material": "Akrylfärg",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 259,
        "index": 13,
        "title": "Red Rain",
        "filename": "259 RED RAIN.jpg",
        "src": "assets/images/259 RED RAIN.jpg",
        "size": "70 * 50 cm",
        "widthM": 0.7,
        "heightM": 0.5,
        "material": "Akrylfärg",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 258,
        "index": 14,
        "title": "Daylight",
        "filename": "258 DAYLIGHT.jpg",
        "src": "assets/images/258 DAYLIGHT.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg, resin",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 257,
        "index": 15,
        "title": "Junior B",
        "filename": "257 JUNIOR B.jpg",
        "src": "assets/images/257 JUNIOR B.jpg",
        "size": "40 * 40 cm",
        "widthM": 0.4,
        "heightM": 0.4,
        "material": "Akrylfärg, paljetter, glitter, resin",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 256,
        "index": 16,
        "title": "Unreal",
        "filename": "256 UNREAL.jpg",
        "src": "assets/images/256 UNREAL.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg, glitterspray, glitter, resin",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 255,
        "index": 17,
        "title": "Waking Light",
        "filename": "255 WAKING LIGHT.jpg",
        "src": "assets/images/255 WAKING LIGHT.jpg",
        "size": "40 * 40 cm",
        "widthM": 0.4,
        "heightM": 0.4,
        "material": "Akrylfärg, resin, glitter",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 254,
        "index": 18,
        "title": "Love Is Magic",
        "filename": "254 LOVE IS MAGIC.jpg",
        "src": "assets/images/254 LOVE IS MAGIC.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg, resin",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 253,
        "index": 19,
        "title": "Bungalow",
        "filename": "253 BUNGALOW.jpg",
        "src": "assets/images/253 BUNGALOW.jpg",
        "size": "27 * 35 cm",
        "widthM": 0.27,
        "heightM": 0.35,
        "material": "Akrylfärg, resin, glitter",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 252,
        "index": 20,
        "title": "Help Me Lose My Mind",
        "filename": "252 HELP ME LOSE MY MIND.jpg",
        "src": "assets/images/252 HELP ME LOSE MY MIND.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akruylfärg, resin",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 251,
        "index": 21,
        "title": "Bright Lights",
        "filename": "251 BRIGHT LIGHTS.jpg",
        "src": "assets/images/251 BRIGHT LIGHTS.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg, glitter, resin",
        "year": "Juli 2024",
        "description": ""
    },
    {
        "id": 250,
        "index": 22,
        "title": "Linnéas Trilogi 3",
        "filename": "250 LINNEAS TRILOGI 3.jpg",
        "src": "assets/images/250 LINNEAS TRILOGI 3.jpg",
        "size": "60 * 73 cm",
        "widthM": 0.6,
        "heightM": 0.73,
        "material": "Spackel",
        "year": "Juli 2024",
        "description": "Skänkt till Linnéa"
    },
    {
        "id": 249,
        "index": 23,
        "title": "Linnéas Trilogi 2",
        "filename": "249 LINNEAS TRILOGI 2.jpg",
        "src": "assets/images/249 LINNEAS TRILOGI 2.jpg",
        "size": "60 * 73 cm",
        "widthM": 0.6,
        "heightM": 0.73,
        "material": "Spackel, akrylfärg",
        "year": "Juli 2024",
        "description": "Skänkt till Linnéa"
    },
    {
        "id": 248,
        "index": 24,
        "title": "Linnéas Trilogi 1",
        "filename": "248 LINNEAS TRILOGI 1.jpg",
        "src": "assets/images/248 LINNEAS TRILOGI 1.jpg",
        "size": "60 * 73 cm",
        "widthM": 0.6,
        "heightM": 0.73,
        "material": "Spackel, akrylfärg",
        "year": "Juli 2024",
        "description": "Skänkt till Linnéa"
    },
    {
        "id": 246,
        "index": 25,
        "title": "Graines D´Étoiles",
        "filename": "246 GRAINES D'ETOILE.jpg",
        "src": "assets/images/246 GRAINES D'ETOILE.jpg",
        "size": "100 * 120 cm",
        "widthM": 1,
        "heightM": 1.2,
        "material": "Akrulfärg, glitter, resin",
        "year": "Juni 2024",
        "description": "Såld till Peter Bodelid"
    },
    {
        "id": 245,
        "index": 26,
        "title": "Fusion 1.0",
        "filename": "245 FUSION 1.0.jpg",
        "src": "assets/images/245 FUSION 1.0.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg, sprayglitter, glitter, resin",
        "year": "Juni 2024",
        "description": ""
    },
    {
        "id": 244,
        "index": 27,
        "title": "Frozen 1.0",
        "filename": "244 FROZEN 1.0.jpg",
        "src": "assets/images/244 FROZEN 1.0.jpg",
        "size": "100 * 40 sm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg, sprayfärg, spryglitter, resin",
        "year": "Juni 2024",
        "description": ""
    },
    {
        "id": 243,
        "index": 28,
        "title": "Flute 1.0",
        "filename": "243 FLUTE 1.0.jpg",
        "src": "assets/images/243 FLUTE 1.0.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg, resin",
        "year": "Maj 2024",
        "description": ""
    },
    {
        "id": 242,
        "index": 29,
        "title": "Atomic #79",
        "filename": "242 ATOMIC 79.jpg",
        "src": "assets/images/242 ATOMIC 79.jpg",
        "size": "30 * 30 cm",
        "widthM": 0.3,
        "heightM": 0.3,
        "material": "Spackel, sprayfärg, akrylfärg, resin",
        "year": "Maj 2024",
        "description": "Skänkt till Tina Joon"
    },
    {
        "id": 241,
        "index": 30,
        "title": "Protected From The Sun 1.0",
        "filename": "241 PROTECTED FROM THE SUN 1.0.jpg",
        "src": "assets/images/241 PROTECTED FROM THE SUN 1.0.jpg",
        "size": "80 * 80 cm",
        "widthM": 0.8,
        "heightM": 0.8,
        "material": "Akrylfärg, poscapennor",
        "year": "2024",
        "description": ""
    },
    {
        "id": 240,
        "index": 31,
        "title": "Rage In Eden",
        "filename": "240 RAGE IN EDEN.jpg",
        "src": "assets/images/240 RAGE IN EDEN.jpg",
        "size": "100 * 40 cm",
        "widthM": 1,
        "heightM": 0.4,
        "material": "Akrylfärg",
        "year": "2024",
        "description": ""
    },
    {
        "id": 239,
        "index": 32,
        "title": "Death Is Everywhere 1.0",
        "filename": "239 DEATH IS EBVERYWHERE.jpg",
        "src": "assets/images/239 DEATH IS EBVERYWHERE.jpg",
        "size": "150 * 50 cm",
        "widthM": 1.5,
        "heightM": 0.5,
        "material": "Sprayfärg, akrylfärg, garn, glitter, resin",
        "year": "2024",
        "description": ""
    },
    {
        "id": 238,
        "index": 33,
        "title": "Bows Side",
        "filename": "238 BOWS side.jpg",
        "src": "assets/images/238 BOWS side.jpg",
        "size": "80 * 80 cm",
        "widthM": 0.8,
        "heightM": 0.8,
        "material": "Sprayfärg, akrylfärg, glitter",
        "year": "Oktober 2023",
        "description": ""
    },
    {
        "id": 238,
        "index": 34,
        "title": "Bows",
        "filename": "238 BOWS.jpg",
        "src": "assets/images/238 BOWS.jpg",
        "size": "80 * 80 cm",
        "widthM": 0.8,
        "heightM": 0.8,
        "material": "Sprayfärg, akrylfärg, glitter",
        "year": "Oktober 2023",
        "description": ""
    },
    {
        "id": 237,
        "index": 35,
        "title": "Burn Baby Burn",
        "filename": "237 BURN BABY BURN.jpg",
        "src": "assets/images/237 BURN BABY BURN.jpg",
        "size": "50 * 50 cm",
        "widthM": 0.5,
        "heightM": 0.5,
        "material": "Sprayfärg, akrylfärg",
        "year": "2023",
        "description": ""
    },
    {
        "id": 236,
        "index": 36,
        "title": "The World Is My Oyster",
        "filename": "236 THE WORLD IS MY OYSTER.jpg",
        "src": "assets/images/236 THE WORLD IS MY OYSTER.jpg",
        "size": "139,5 * 56,5 cm",
        "widthM": 1.395,
        "heightM": 0.565,
        "material": "Sprayfärg, akrylfärg",
        "year": "Augusti 2023",
        "description": ""
    },
    {
        "id": 235,
        "index": 37,
        "title": "Connected Dots 1.0",
        "filename": "235 CONNECTED DOTS 1.0.jpg",
        "src": "assets/images/235 CONNECTED DOTS 1.0.jpg",
        "size": "50 * 50 cm",
        "widthM": 0.5,
        "heightM": 0.5,
        "material": "Sprayfärg, akrylfärg",
        "year": "Augusti 2023",
        "description": ""
    },
    {
        "id": 234,
        "index": 38,
        "title": "Signs",
        "filename": "234 SIGNS.jpg",
        "src": "assets/images/234 SIGNS.jpg",
        "size": "73 * 60 cm",
        "widthM": 0.73,
        "heightM": 0.6,
        "material": "Sprayfärg, akrylfärg",
        "year": "Augusti 2023",
        "description": ""
    },
    {
        "id": 233,
        "index": 39,
        "title": "Chaos 1.0",
        "filename": "233 CHAOS 1.0.jpg",
        "src": "assets/images/233 CHAOS 1.0.jpg",
        "size": "40 * 40 cm",
        "widthM": 0.4,
        "heightM": 0.4,
        "material": "Sprayfärg, akrylfärg",
        "year": "Augusti 2023",
        "description": ""
    },
    {
        "id": 232,
        "index": 40,
        "title": "Wire",
        "filename": "232 WIRE.jpg",
        "src": "assets/images/232 WIRE.jpg",
        "size": "61 * 50 cm",
        "widthM": 0.61,
        "heightM": 0.5,
        "material": "Spratfärg, akrylfärg",
        "year": "Augusti 2023",
        "description": ""
    },
    {
        "id": 231,
        "index": 41,
        "title": "Jungle 2.0",
        "filename": "231 JUNGLE 2.0.jpg",
        "src": "assets/images/231 JUNGLE 2.0.jpg",
        "size": "61* 50 cm",
        "widthM": 0.61,
        "heightM": 0.5,
        "material": "Sprayfärg, akrylfärg",
        "year": "Augusti 2023",
        "description": ""
    },
    {
        "id": 230,
        "index": 42,
        "title": "Peace.oooo",
        "filename": "230 PEACE.OOOO.jpg",
        "src": "assets/images/230 PEACE.OOOO.jpg",
        "size": "61 * 50 cm",
        "widthM": 0.61,
        "heightM": 0.5,
        "material": "Sprayfärg, akrylfärg, glitter",
        "year": "Augusti 2023",
        "description": ""
    },
    {
        "id": 229,
        "index": 43,
        "title": "The Evil Eye",
        "filename": "229 THE EVIL EYE.jpg",
        "src": "assets/images/229 THE EVIL EYE.jpg",
        "size": "50 * 61 cm",
        "widthM": 0.5,
        "heightM": 0.61,
        "material": "Sprayfärg, akrylfärg, glitter",
        "year": "Augusti 2023",
        "description": ""
    },
    {
        "id": 228,
        "index": 44,
        "title": "Limelight",
        "filename": "228 LIMELIGHT.jpg",
        "src": "assets/images/228 LIMELIGHT.jpg",
        "size": "50 * 50 cm",
        "widthM": 0.5,
        "heightM": 0.5,
        "material": "Sprayfärg, akrylfärg, glitter",
        "year": "Juli 2023",
        "description": ""
    },
    {
        "id": 227,
        "index": 45,
        "title": "The Big Chair",
        "filename": "227 THE BIG CHAIR.jpg",
        "src": "assets/images/227 THE BIG CHAIR.jpg",
        "size": "50 * 61 cm",
        "widthM": 0.5,
        "heightM": 0.61,
        "material": "Sprayfärg, akrylfärg",
        "year": "Juli 2023",
        "description": ""
    },
    {
        "id": 226,
        "index": 46,
        "title": "Movement 1.0",
        "filename": "226 MOVEMENT.jpg",
        "src": "assets/images/226 MOVEMENT.jpg",
        "size": "40 * 60 cm",
        "widthM": 0.4,
        "heightM": 0.6,
        "material": "Sprayfärg, akrylfärg, glitter",
        "year": "Juli 2023",
        "description": ""
    },
    {
        "id": 225,
        "index": 47,
        "title": "Human 1.0",
        "filename": "225 HUMAN 1.0.jpg",
        "src": "assets/images/225 HUMAN 1.0.jpg",
        "size": "50 * 61 cm",
        "widthM": 0.5,
        "heightM": 0.61,
        "material": "Sprayfärg, akrylfärg",
        "year": "Juli 2023",
        "description": ""
    },
    {
        "id": 224,
        "index": 48,
        "title": "Exploding Woods",
        "filename": "224 EXPLODING WOODS.jpg",
        "src": "assets/images/224 EXPLODING WOODS.jpg",
        "size": "50 * 61 cm",
        "widthM": 0.5,
        "heightM": 0.61,
        "material": "Sprayfärg, akrylfärg",
        "year": "Juli 2023",
        "description": ""
    },
    {
        "id": 223,
        "index": 49,
        "title": "Halo 1.1",
        "filename": "223 HALO 1.1.jpg",
        "src": "assets/images/223 HALO 1.1.jpg",
        "size": "30 * 90 cm",
        "widthM": 0.3,
        "heightM": 0.9,
        "material": "Sprayfärg, akrylfärg, metall, glas, kork",
        "year": "Juli 2023",
        "description": ""
    },
    {
        "id": 222,
        "index": 50,
        "title": "Equinoxe 1.2",
        "filename": "222 EQUINOXE 1.1.jpg",
        "src": "assets/images/222 EQUINOXE 1.1.jpg",
        "size": "80 * 80 cm",
        "widthM": 0.8,
        "heightM": 0.8,
        "material": "Sprayfärg, akrylfärg",
        "year": "Juli 2023",
        "description": ""
    }
];
